:: Installs CHIP8 on your system but does not add it to the path
:: Administrator permission is needed to install CHIP8
@ECHO OFF
ECHO Configuring CMake ...
cmake -B ../build -DCMAKE_BUILD_TYPE=Release ..
ECHO Building CHIP8 ...
cmake --build ../build --config Release --target CHIP8
ECHO Installing CHIP8 ...
cmake --install ../build/src --config Release