macro(CHIP8_Determine_Compiler)
    # We determine the compiler so we can do some optimization for a specific compiler
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
    add_compile_definitions(COMPILER_GCC)
    elseif(CMAKE_C_COMPILER_ID STREQUAL "Clang")
    add_compile_definitions(COMPILER_CLANG)
    elseif(CMAKE_C_COMPILER_ID STREQUAL "MSVC")
    add_compile_definitions(COMPILER_MSVC)
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
    add_compile_definitions(COMPILER_INTEL)
    else()
    add_compile_definitions(COMPILER_UNKNOWN)    
    endif()
endmacro(CHIP8_Determine_Compiler)
