name: Build CHIP-8
on:
  pull_request:
    branches: ["master"]
    paths-ignore:
     - '**/*.md'    # Markdown
     - '**/*.bat'   # Scripts
     - '**/*.sh'
     - '**/*.cp8'   # CHIP-8 assembly language
     - '**/*.html'  # Documentation
     - '**/*.js'
     - '**/*.png'
     - '**/*.css'
     - '**/*.dox'
     - '**/*.svg'
     - '**/*.bmp'
     - '**/*.ico'
jobs:
  build:
    runs-on: ${{matrix.operatingsystems}}
    env:
      BUILD_TYPE: ${{matrix.buildtypes}}
    strategy:
      matrix:
        operatingsystems: [windows-latest, ubuntu-latest, macos-latest] 
        buildtypes: [Debug, Release]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build Emulator
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      