name: Tests

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ${{matrix.operatingsystems}}
    env:
      BUILD_TYPE: ${{matrix.buildtypes}}

    strategy:
      matrix:
        operatingsystems: [ubuntu-latest] 
        buildtypes: [Release] 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      # include submodules
      with:
        submodules: recursive

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master    

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCP8_BUILD_TESTS=ON -G Ninja

    - name: Building Tests
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target CHIP-8_Frontend_Tests

    - name: Running tests
      run: cd build && ctest -C ${{env.BUILD_TYPE}} 
